AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'spec/*_helper.rb'
  TargetRubyVersion: 2.4.4
  ExtraDetails: true
  DisplayStyleGuide: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
